In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data = pd.read_csv("/content/drive/MyDrive/edutech/edu1.csv")

In [ ]:
data['Lecture 4'] = pd.to_numeric(data['Lecture 4'],errors='coerce')

In [ ]:
data.head()

Day  Month    Year  Lecture 1  ...  Lecture 3  Lecture 4  Lecture 5  Overall pred
0  4.0    5.0  2021.0        2.0  ...        2.0        0.0        2.0           2.0
1  5.0    5.0  2021.0        0.0  ...        0.0        0.0        2.0           0.0
2  6.0    5.0  2021.0        4.0  ...        4.0        0.0        4.0           4.0
3  7.0    5.0  2021.0        3.0  ...        0.0        1.0        1.0           1.0
4  8.0    5.0  2021.0        0.0  ...        3.0        0.0        4.0           0.0

[5 rows x 9 columns]

In [ ]:
data.shape

(23, 9)

In [ ]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [ ]:
clean_dataset(data)

Day  Month    Year  ...  Lecture 4  Lecture 5  Overall pred
0    4.0    5.0  2021.0  ...        0.0        2.0           2.0
1    5.0    5.0  2021.0  ...        0.0        2.0           0.0
2    6.0    5.0  2021.0  ...        0.0        4.0           4.0
3    7.0    5.0  2021.0  ...        1.0        1.0           1.0
4    8.0    5.0  2021.0  ...        0.0        4.0           0.0
5    9.0    5.0  2021.0  ...        4.0        4.0           0.0
6   10.0    5.0  2021.0  ...        2.0        3.0           3.0
7   11.0    5.0  2021.0  ...        2.0        3.0           3.0
8   12.0    5.0  2021.0  ...        2.0        3.0           1.0
9   13.0    5.0  2021.0  ...        4.0        4.0           0.0
10  14.0    5.0  2021.0  ...        0.0        4.0           4.0
11  15.0    5.0  2021.0  ...        0.0        4.0           0.0
12  16.0    5.0  2021.0  ...        2.0        4.0           0.0
13  17.0    5.0  2021.0  ...        2.0        3.0           2.0
14  18.0    5.0  2021.0  ...        4.0        0.0           4.0

[15 rows x 9 columns]

In [ ]:
X = data.drop(['Overall pred'],axis=1)
Y = data['Overall pred']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
lm = LogisticRegression()

In [ ]:
lm.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
predictions = lm.predict(X_test)
from sklearn import metrics
y_pred = lm.predict(X_test)
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, y_pred)))

Mean Absolute Error: 0.6
Mean Squared Error: 1.0
Root Mean Squared Error: 1.0


In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(classification_report(y_pred,Y_test))

              precision    recall  f1-score   support

         0.0       1.00      0.75      0.86         4
         2.0       0.00      0.00      0.00         0
         3.0       0.00      0.00      0.00         1

    accuracy                           0.60         5
   macro avg       0.33      0.25      0.29         5
weighted avg       0.80      0.60      0.69         5



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print(confusion_matrix(y_pred,Y_test))

[[3 1 0]
 [0 0 0]
 [0 1 0]]


In [ ]:
import pickle

In [ ]:
pickle_final=open("lm.pkl","wb")

In [ ]:
pickle.dump(lm,pickle_final)

In [ ]:
pickle_final.close()